default_stages: [commit, push, merge-commit]
default_language_version:
    python: python3.8
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-docstring-first
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: pretty-format-json
        args:
          - "--autofix"
          - "--indent=4"
          - "--no-sort-keys"
    -   id: trailing-whitespace

-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black

ci:
    autofix_commit_msg: |
        [pre-commit.ci] Auto fixes from pre-commit.
    autofix_prs: true
    autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
    autoupdate_schedule: weekly
    skip: []
    submodules: false
